### PR TITLE
Linting for release

### PR DESCRIPTION
**Pull request by muffato**
This is a PR to solve the issues flagged by `nf-core lint` in #28 . I've started fixing a few, but @DLBPointon can you check the other ones ?

- [x] _when: condition has been removed_
      I've added them back b9d2630334e96623164ab7e8d51e38f28b794382
- [x] _Found tuple but no channel names_
      The parser was confused by the whitespace 68b369b4cfbaf0e430d31c69ea95fd6fcb0a96fb
- [x] _Module does not emit software version_
      Only `modules/local/reformat_intersect.nf` needs fixing
- [x] _Non-standard labels found_
     `process_tiny` is not recognised. Switched to `process_single` f71aeb2275505650631e6f5398c124b56f71510e
- [x] _Specified label appears to contain non-alphanumerics_ and _Standard process label not found_
      It looks like `nf-core lint` didn't like the double quotes 501572c5bc8341022a3e491f2bf2e5560d366a62
- [x] _'meta' map not emitted in output channel(s)_
      This is `get_largest_scaff.nf` 
- [x] _Config manifest.version should not contain dev for a release:_ and _manifest.version was not numeric_
     You need to bump the version number in `nextflow_config` and other files

I think these ones don't need fixing, but please confirm:

- [x] _Unable to connect to container URL_
  `nf-core lint` seems unable to parse / verify `docker.io/ubuntu:20.04`
- [x] _New version available_
  The versions being used have been validated in production. We don't want to change them now.
- [x] _No template found in shell block_
 That's because it expects `""" ... """` but you use `$/ ... /$`. I guess that's on purpose to simplify the handling of `$` ?
- [x] _Container versions do not match_
      I think it's complaining that the Singularity and Docker versions mismatch

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/curationpretext/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the sanger-tol/curationpretext _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Comment by DLBPointon** [comment]
Hi @muffato 

Thanks for writing this up.
- I've now added the version output to reformat_intersect
- For get_largest_scaff, this module outputs an env, I can't put this in a tuple can i? Would you want another channel as output to output the meta?
- manifest.version has been corrected in the nextflow.config, where else is it changed? I see alot of files that reference manifest.version so don't need updating.

---
Can't be fixed
- Yes, I see the same lint error. NF-core seems to not like the docker.io prefix. I don't think I can override that error.
- I agree, versions should be kept the same until we can properly validate the new version.
- Yes, i'm using `$/ ... /$` here to better use bash. I'm pretty sure we used this with """...""" and awk was not having it.
- I presume so.

**Comment by muffato** [comment]
> * For get_largest_scaff, this module outputs an env, I can't put this in a tuple can i? Would you want another channel as output to output the meta?

Can you try putting the `env` together with `meta` in a tuple ? If it works, we're good. Otherwise, let's dismiss this CI test

> * manifest.version has been corrected in the nextflow.config, where else is it changed? I see alot of files that reference manifest.version so don't need updating.

Here are all the places where we have the version number: https://github.com/sanger-tol/genomenote/pull/127/files (exclude the Python script). Make sure all those files are updated in this PR here.

**Comment by muffato** [comment]
Super ! I fixed the CI error, the last linting error and a few warnings. All good now

**Comment by muffato** [comment]
Up to you @DLBPointon to _Approve_ and merge

**Review by DLBPointon — APPROVED** [review]

**Comment by DLBPointon** [comment]
> Up to you @DLBPointon to _Approve_ and merge

Thanks for all the help with this @muffato !

**Pull request merged**
