### PR TITLE
Dp24 spelling

### PR DESCRIPTION
**Pull request by DLBPointon**
Module updates and container changes.

Version upped to V1.1

### CODE REVIEW

**Comment by DLBPointon** [comment]
Will hopefully solve issues with #42 and #43

**Comment by DLBPointon** [comment]
Just remembered that CHANGELOG needs updating. I'll sort that out Monday!

**Review by muffato — COMMENTED** [review]
I can confirm that:

- all containers are Anaconda-free
- no occurrence of `defaults` & co in the `environment.yml` files

You also need to update:

-  `CITATIONS.md` (there's a reference to Anaconda)
- `libs/Utils.groovy` (to remove `defaults` from the channel list)

I've kicked off a `test_full` run and will check it on Monday, though I'm not sure I can fully assess the outputs make sense

**Comment by muffato** [comment]
`test_full` was actually quick ! The output files are identical 👍🏼

**Comment by muffato** [comment]
Ah wait, there are still occurrences of `quay.io/sanger-tol/pretext:0.0.2-yy5-c3` (#42) !
```
modules/local/pretext_graph.nf:    container "quay.io/sanger-tol/pretext:0.0.2-yy5-c3"
modules/nf-core/pretextmap/main.nf:    container "quay.io/sanger-tol/pretext:0.0.2-yy5-c3"
modules/nf-core/pretextmap/pretextmap.diff:+    container "quay.io/sanger-tol/pretext:0.0.2-yy5-c3"
```

**Comment by DLBPointon** [comment]
Thanks for the review Matthieu, I've now just got to update Changelog. But currently debugging #43 and #44.

**Review by muffato — APPROVED** [review]

**Pull request merged**
