### PR TITLE
add map_order

### PR DESCRIPTION
**Pull request by yumisims**
## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
- [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/sanger-tol/curationpretext/tree/master/.github/CONTRIBUTING.md)
- [ ] If necessary, also make a PR on the sanger-tol/curationpretext _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker --outdir <OUTDIR>`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

### CODE REVIEW

**Review by DLBPointon — APPROVED** [review]
Thanks for sorting this out @yumisims

**Comment by DLBPointon** [comment]
Why is it trying to lint a binary all of a sudden?

**Comment by yumisims** [comment]
need to containerise the find_telomere executable, will do it tomorrow. @DLBPointon

**Comment by DLBPointon** [comment]
> need to containerise the find_telomere executable, will do it tomorrow. @DLBPointon

Sounds good to me, thanks @yumisims

**Pull request merged**
